name: create or update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: auto/pr-something
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          date > date.txt

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add date.txt
          git checkout -b ${BRANCH}
          git commit -m "(bot) update date.txt"
          git push -f -u origin ${BRANCH}

      - uses: actions/github-script@v6
        with:
          script: |
            const { BRANCH } = process.env
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `jeongukjae:${BRANCH}`
            });
            console.log(pulls)
            if (pulls.length == 0) {
              github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: "main",
                head: `jeongukjae:${BRANCH}`,
                title: "Automated PR!",
              })
            } else {
              console.log(pulls[0])
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pulls[0].id,
                body: "PR is updated",
              });
            }
